name: gradle-versioning
on:
  push:
    paths:
      - 'gradle.properties'

jobs:
  create-version-tag:
    name: Create version Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: 'main'
      - name:  Get project version with gradle
        id: project-version
        run: grdversion=$(cat 'gradle.properties' | grep -e ^version) && array=(${grdversion//=/ }) && echo "VERSION=v${array[1]}" >> $GITHUB_OUTPUT
      - name: Create git tag
        run: |
          git config user.name = "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag -a "${{ steps.project-version.outputs.VERSION }}" -m "Created new tag version ${{ steps.project-version.outputs.VERSION }}"
          git push origin "${{ steps.project-version.outputs.VERSION }}"
